import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "on-tertiary": "#ffffff",
        outline: "#777683",
        "on-surface-variant": "#464652",
        "tertiary-fixed-dim": "#3adfab",
        "on-tertiary-container": "#00c190",
        "on-primary-fixed": "#04006d",
        "on-primary": "#ffffff",
        "secondary-container": "#d5e3fc",
        "secondary-fixed": "#d5e3fc",
        "on-primary-fixed-variant": "#373a9b",
        "outline-variant": "#c7c5d4",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#57657a",
        "inverse-primary": "#c0c1ff",
        "primary-fixed": "#e1e0ff",
        "primary-container": "#1a5a9e",
        "on-tertiary-fixed": "#002116",
        "surface-tint": "#4f54b4",
        "surface-dim": "#d8dadc",
        background: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#60fcc6",
        "on-tertiary-fixed-variant": "#00513b",
        "tertiary-container": "#004834",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#b9c7df",
        primary: "#2f6fb8",
        "on-secondary-fixed-variant": "#3a485b",
        surface: "#f7f9fb",
        error: "#ba1a1a",
        "on-primary-container": "#9da1ff",
        secondary: "#515f74",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-high": "#e6e8ea",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed": "#0d1c2e",
        "on-surface": "#191c1e",
        tertiary: "#002f21",
        "inverse-on-surface": "#eff1f3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
